// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Tkbf4nzH6l4jRJtXAM7hIMtcL1oQU4A',
    appId: '1:808262353334:android:3f68ddb11f0d506b8d8117',
    messagingSenderId: '808262353334',
    projectId: 'solutions-sol',
    storageBucket: 'solutions-sol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjNYEVthRGrQ5odD6r2pr44GNFoSUswww',
    appId: '1:808262353334:ios:ecd383b2249f190f8d8117',
    messagingSenderId: '808262353334',
    projectId: 'solutions-sol',
    storageBucket: 'solutions-sol.appspot.com',
    androidClientId: '808262353334-6b919khgr32hcqgqqc3ch2vj8u789ilf.apps.googleusercontent.com',
    iosClientId: '808262353334-5d40mblsjul0p76ouf707l4ku5uifdp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.transvitiAssessmentTest',
  );
}
